 ###################################### 线上环境
 server:  
 server.port: 80  
 server.context-path: /shb_web
 # server.session-timeout: 30   
 # server.tomcat.max-threads: 0  
 # server.tomcat.uri-encoding: UTF-8 
 ## 数据源配置 
 spring:
    datasource:
        url: jdbc:mysql://rm-m5e2q1z177ct84c01.mysql.rds.aliyuncs.com:3306/shb_new?useUnicode=true&characterEncoding=utf-8
        username: shb
        password: Shanhaibian6688
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        # spring.http.multipart.maxFileSize= 10240000000
        # spring.mvc.view.prefix= /WEB-INF/jsp/
        # spring.mvc.view.suffix= .jsp
        
    http:
        multipart.maxFileSize: 10240000000
        
 mvc:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
        

 jmx:
    default-domain: shbWeb

 endpoints: 
    jmx:
        domain: shbWeb
        unique-names: true
        
 devtools:
    restart:
        additional-paths: com\\shb\\web
        
 thymeleaf:
    cache: false
        
        ###########################redis######################################################
    redis:
        host: 127.0.0.1
        password: 
        port: 6379
    pool:   
        max-idle: 100
        min-idle: 1
        max-active: 1000
        max-wait: -1 
         
        ## Mybatis 配置
 mybatis:
  # type-aliases-package: com.shb.weixin.mobile
  # mapper-locations: classpath:mapper/*.xml
  # config-location: classpath:mybatis-config.xml
 logging: 
  logging.config=classpath:logback.xml


