 ###################################### 测试环境
 server:  
 server.port: 8088  

 server.context-path: /shb_web
 server.session-timeout: 30   
 server.tomcat.max-threads: 0  
 server.tomcat.uri-encoding: UTF-8  
 server.compression.enabled: true
 server.compression.mime-types: application/json,application/xml,text/html,text/xml,text/plain


 
 ## 数据源配置 
 spring:
    datasource:
        url: jdbc:mysql://192.168.3.128:3306/shb?useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        removeAbandoned: true
        removeAbandonedTimeout: 1800
        # spring.http.multipart.maxFileSize= 10240000000
        # spring.mvc.view.prefix= /WEB-INF/jsp/
        # spring.mvc.view.suffix= .jsp
        
    http:
        multipart.maxFileSize: 10240000000
        
 mvc:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
        
 devtools:
    restart:
        additional-paths: com\\shb\\web
        
 thymeleaf:
    cache: false
        
        ###########################redis######################################################
 redis:
    host: 127.0.0.1
    password: 
    port: 6379
    timeout: 0
 pool:   
    max-idle: 100
    min-idle: 0
    max-active: 300
    max-wait: 1000 
         
        ## Mybatis 配置
 mybatis:
  # type-aliases-package: com.shb.web.mobile
  # mapper-locations: classpath:mapper/*.xml
  # config-location: classpath:mybatis-config.xml
 logging: 
  logging.config=classpath:logback.xml


